---
- name: create the backend directory
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: get extracted artifact into backend
  unarchive: # unarchive a file in src to dest
    src: ~/project/artifact.tar.gz
    dest: ~/backend  # remote EC2
    mode: 0755
    owner: ubuntu
    group: ubuntu

- name: execute node
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start

