---
- name: create the backend directory
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: get extracted artifact into backend
  unarchive: # unarchive a file in src to dest
    src: ~/project/artifact.tar.gz
    dest: ~/backend  # remote EC2
    mode: 0755
    owner: ubuntu
    group: ubuntu

- name: execute node
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start

# - name: Copy backend files
#   become: true
#   copy:
#     src: backend.tar.gz
#     dest: /home/ubuntu/backend.tar.gz

# - name: Start PM2
#   shell: |
#     cd /home/ubuntu/
#     tar xzvf backend.tar.gz
#     # mv home/circleci/project/backend .
#     cd backend
#     sudo npm install -g npm@latest
#     sudo npm install -g webpack-dev-server
#     sudo npm install
#     sudo npm run build
#     sudo pm2 start npm --name backend -- start
